#!/bin/sh

go run main.go < specs.input > specs.output     || exit 1

OUTPUT=$(
  git diff specs.output > /dev/stdout || exit 1
)                                               || exit 1

[[ "$OUTPUT" = "" ]]                            && exit 0

echo "$OUTPUT"
git checkout specs.output

exit 1
